# Generated by Django 3.0 on 2019-12-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
