# Generated by Django 3.0 on 2020-03-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
                ('Month', models.CharField(max_length=10)),
                ('Gross_Salary', models.IntegerField()),
                ('Professional_Tax', models.IntegerField()),
                ('Group_Ins', models.IntegerField()),
                ('Gpf', models.IntegerField()),
                ('Hba', models.IntegerField()),
                ('Service_Ded', models.IntegerField()),
                ('PLI', models.IntegerField()),
                ('LIC', models.IntegerField()),
                ('Trans_Allow', models.IntegerField()),
                ('Month_Ded', models.IntegerField()),
                ('first_half_ded', models.IntegerField()),
                ('second_half_ded', models.IntegerField()),
                ('DA_Diff', models.IntegerField()),
                ('HRA_Diff', models.IntegerField()),
                ('Trans_Exp', models.IntegerField()),
                ('PPF', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='income_Ded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=10)),
                ('Pro_Tax', models.IntegerField()),
                ('Trans_Allow', models.IntegerField()),
                ('HBA_Intr', models.IntegerField()),
                ('Mediclaim', models.IntegerField()),
                ('P_H_Ded', models.IntegerField()),
                ('Donation', models.IntegerField()),
                ('Other_Ded', models.IntegerField()),
                ('Other_income', models.IntegerField()),
                ('GPF_Contr', models.IntegerField()),
                ('State_Gvt_Ins', models.IntegerField()),
                ('Repay_HBA', models.IntegerField()),
                ('NSC_Purchase', models.IntegerField()),
                ('PPF', models.IntegerField()),
                ('LIC_Prem', models.IntegerField()),
                ('PLI_Prem', models.IntegerField()),
                ('Edu_Fee', models.IntegerField()),
                ('JSA', models.IntegerField()),
                ('Infra_Bond', models.IntegerField()),
                ('Equity_Link', models.IntegerField()),
                ('Other_Eligible', models.IntegerField()),
                ('Total_Ded', models.IntegerField()),
                ('Total_Income', models.IntegerField()),
                ('Net_Tax_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Itr21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id2', models.CharField(max_length=10)),
                ('income', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Net_Tax_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Textfield',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=50)),
                ('Label', models.CharField(default='', max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_tax.Form')),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('UserId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=255)),
                ('PAN', models.CharField(max_length=10)),
                ('Aadhar', models.CharField(max_length=12)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=10)),
                ('UseImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
