# Generated by Django 3.0 on 2020-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
