# Generated by Django 3.0 on 2020-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0003_form_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='Label',
        ),
        migrations.AddField(
            model_name='textfield',
            name='Label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
